"""
Django settings for trainpad project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os, environ
from django.utils.translation import gettext_lazy as _
from distutils.util import strtobool

if os.name == 'nt':
    VENV_BASE = os.environ['VIRTUAL_ENV']
    os.environ['PATH'] = os.path.join(VENV_BASE, 'Lib\\site-packages\\osgeo') + ';' + os.environ['PATH']
    os.environ['PROJ_LIB'] = os.path.join(VENV_BASE, 'Lib\\site-packages\\osgeo\\data\\proj') + ';' + os.environ['PATH']
    
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env( # set casting, default value
    DEBUG=(bool, False)
)
environ.Env.read_env( os.path.join(BASE_DIR, '.env') )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1z8o)2k*!=_w=@hx+5y5ob3^px%^@5+rvznlu(2lv&8-@hhq7r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (os.getenv('APP_DEBUG', 'False') == 'True')

ALLOWED_HOSTS = env("APP_SERVERNAMES").split(" ")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'portal',
    'dashboard',
    'user',
    'gym',
    
    'channels',
    'channels_redis',
    'modeltranslation',
    'versatileimagefield',
    'rest_framework',
    'oauth2_provider',    
    'ckeditor_uploader',
    'ckeditor',
    'rosetta',
    'debug_toolbar',
    'push_notifications',
    'django_crontab',
    'django_celery_beat'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

ROOT_URLCONF = 'trainpad.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / "templates" ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries':{
            'my_filters': 'dashboard.templatetags.my_filters',
            
            }

        },
    },
]

WSGI_APPLICATION = 'trainpad.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

APP_PRODUCTION = True # if os.getenv("APP_PRODUCTION", "False") == "True" else False
DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.postgresql',
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': env("DB_PRO_NAME") if APP_PRODUCTION else env("DB_DEV_NAME"),
        'USER': env("DB_PRO_USERNAME") if APP_PRODUCTION else env("DB_DEV_USERNAME"),
        'PASSWORD': env("DB_PRO_PASSWORD") if APP_PRODUCTION else env("DB_DEV_PASSWORD"),
        'HOST': env("DB_PRO_HOST") if APP_PRODUCTION else env("DB_DEV_HOST"),
        'PORT': env("DB_PRO_PORT") if APP_PRODUCTION else env("DB_DEV_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH2_COOKIE = "refresh_token"

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    #BASE_DIR / 'static/'
    os.path.join(BASE_DIR, 'static'),
]


# multi languages
USE_I18N = True

MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
LANGUAGES = (
    ('en', _('English')),
    ('ar', _('Arabic')),
)
MODELTRANSLATION_LANGUAGES = ('en', 'ar')
LOCALE_PATHS = [
    BASE_DIR / 'trainpad/locale/',
]

AUTH_USER_MODEL = 'portal.User'

SMS_USERNAME= os.getenv('SMS_USERNAME')
SMS_PASSWORD= os.getenv('SMS_PASSWORD')

CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_UPLOAD_PATH = "ckeditor/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_CONFIGS = {
    'default': {
       'toolbar_Full': [
            ['Bold', 'Italic', 'Underline', 'Undo', 'Redo'],
            ['Link', 'Unlink'],
            # ['Image', 'Flash', 'Table', 'HorizontalRule'],
            # ['TextColor', 'BGColor'],
            # ['Smiley', 'SpecialChar'], ['Source'],
            ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
            # ['NumberedList','BulletedList'],
            ['Indent','Outdent'],           
        ],
        'width': 'auto',
        'extraPlugins': 'justify,liststyle,indent',
        "removePlugins": "stylesheetparser",
        'allowedContent': True,
    },
   }

OAUTH2_PROVIDER = {
    # this is the list of available scopes
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'}
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ),
    
}

CACHES = {
'default': {
    'BACKEND':  'django.core.cache.backends.filebased.FileBasedCache',	
    'LOCATION': os.path.join(BASE_DIR, 'log') ,	
}}

#sendgrig email
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_TLS = bool(strtobool(os.getenv('EMAIL_USE_TLS', 'True')))
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# celery
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Dhaka'

# FCM Token
PUSH_NOTIFICATIONS_SETTINGS = {
    "FCM_API_KEY": os.getenv('APP_FCM_API_KEY'),
}

ASGI_APPLICATION = "trainpad.asgi.application" #routing.py will be created later
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

CRONJOBS = [
    ('30 16 * * *', 'portal.cron.daily_workout_remainder'),
    
]

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'